--- 
services: 
  web: 
    build: 
      context: "."
    container_name: hrpc_app_container
    image: hrpc-app
    ports: 
      - "80:8080"
      - "443:9999"
    restart: always
    volumes: 
      - "./logs:/usr/local/tomcat/logs/"
version: "3.3"
